### ISSUE TITLE
Hi Teddy! I'm dumb and can't get this to work 

### ISSUE THREAD

**Issue by sheinasim-USDA** [tedsta/cube-scout#1]
I installed opencv and i'm running it in a virtual environment.  I'm getting the error:

(cv) pi@homeslice:~/cube-scout $ python cubescout.py 0 -s
Loading training data...
Training face recognizer...
Traceback (most recent call last):
  File "cubescout.py", line 227, in <module>
    main()
  File "cubescout.py", line 82, in main
    model = createLBPHFaceRecognizer()
NameError: global name 'createLBPHFaceRecognizer' is not defined

I'm running opencv3.0.0 on a raspberry pi 3 Debian version Jessie if that makes a difference.  Do I have to install opencv2.4.9?

**Comment by tedsta** [comment]
The face recognizer functionality in OpenCV is part of the "contrib" module. I guess they pulled it out of the official OpenCV distribution for OpenCV 3. I've never tested with OpenCV 3, but if you build and install the contrib module here it should work: https://github.com/Itseez/opencv_contrib
